apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: prueba-kubernete
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /dev-prueba-kubernete(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: prueba-kubernete
                port:
                  number: 80