apiVersion: v1
kind: Service
metadata:
  namespace: pdn
  name: prueba-kubernete
spec:
  selector:
    app: prueba-kubernete
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080